#!/bin/bash

#this file should configure the capabilities of my systems

K="\[\033[0;30m\]"    # black
R="\[\033[0;31m\]"    # red
G="\[\033[0;32m\]"    # green
Y="\[\033[0;33m\]"    # yellow
B="\[\033[0;34m\]"    # blue
M="\[\033[0;35m\]"    # magenta
C="\[\033[0;36m\]"    # cyan
W="\[\033[0;37m\]"    # white
# emphasized (bolded) colors
EMK="\[\033[1;30m\]"
EMR="\[\033[1;31m\]"
EMG="\[\033[1;32m\]"
EMY="\[\033[1;33m\]"
EMB="\[\033[1;34m\]"
EMM="\[\033[1;35m\]"
EMC="\[\033[1;36m\]"
EMW="\[\033[1;37m\]"
# background colors
BGK="\[\033[40m\]"
BGR="\[\033[41m\]"
BGG="\[\033[42m\]"
BGY="\[\033[43m\]"
BGB="\[\033[44m\]"
BGM="\[\033[45m\]"
BGC="\[\033[46m\]"
BGW="\[\033[47m\]"



export config_fancy_effects=0
export config_hdpi=0
export config_ssh_keys=""
export config_dmenu_cache="dmenu_path >~/.cache/dmenu_run &"
export config_seafile=0
export config_locker="light-locker"
export config_wallpaper_command="~/.config/herbstluftwm/wallpaper.sh &"
export config_gui_editor="subl3"
export config_editor="nano"
export config_prompt_user_color="$EMC"
export config_prompt_host_color="$W"
export config_prompt_hostname="$HOSTNAME"

case "$HOSTNAME" in
    stealthpad)
        export config_fancy_effects=1
        export config_hdpi=1
        export config_ssh_keys="~/.ssh/mykey ~/.ssh/cipkey"
        export config_seafile=1
        export config_prompt_user_color=$EMY
        export config_prompt_host_color=$EMM
        export config_prompt_hostname="x240"
        export config_dmenu_cache="~/.config/herbstluftwm/dmenu_run_cache &"
        ;;
    irene-ThinkPad)
    	export config_ssh_keys="~/.ssh/mykey"
        export config_wallpaper_command="nitrogen --restore &"
        export config_prompt_user_color=$G
        export config_prompt_host_color=$EMB
        export config_prompt_hostname="z61"
    	;;
    faui49man*)
    	export config_ssh_keys="~/.ssh/i4 ~/.ssh/i4github ~/.ssh/cipkey"
    	export config_wallpaper_command="feh --bg-center /usr/share/backgrounds/Early_Morning_by_Robert_Katzki.jpg &"
        export config_locker="i3lock"
        export config_gui_editor="subl"
        export config_prompt_user_color=$B
        export config_prompt_host_color=$EMM
        export config_prompt_hostname=`echo $HOSTNAME | cut -d9 -f2`
        export config_dmenu_cache="~/.config/herbstluftwm/dmenu_run_cache &"
        ;;
    faui0*)
        export config_wallpaper_command="(sleep 5 && wallpaper autum)&"
    	export config_ssh_keys="~/.ssh/cipkey"
    	export config_locker="xlock"
        export config_prompt_user_color=$C
        export config_prompt_host_color=$EMG
        export config_prompt_hostname="$HOSTNAME"
        ;;
    squarez)
        export config_prompt_user_color=$B
        export config_prompt_host_color=$EMG
        ;;
    horologium.uberspace.de)
        export config_prompt_user_color=$R
        export config_prompt_host_color=$EMC
        export config_prompt_hostname="uber"
        ;;   
    *)
        ;;
esac