#!/bin/bash
##################
##	BASH PROMPT	##
##################

function timer_start {
  timer=${timer:-$SECONDS}
}

function timer_stop {
  timer_show=$(($SECONDS - $timer))
  unset timer
}


## Fancy PWD display function
## The home directory (HOME) is replaced with a ~
## The last pwdmaxlen characters of the PWD are displayed
## Leading partial directory names are striped off
## /home/me/stuff          -> ~/stuff               if USER=me
## /usr/share/big_dir_name -> ../share/big_dir_name if pwdmaxlen=20

#run each time
function bash_prompt_command() {
    # set an error string for the prompt, if applicable
    if [ $? -eq 0 ]; then
        local ERRPROMPT=""
    else
        local ERRPROMPT='->$[$?]\n\a'
    fi

    # echo a bell-character if execution took more than 3 seconds
    timer_stop
    if [ $timer_show -gt 3 ]; then
        #echo -e
        local TIMES='[$timer_show s]\n\a'
    else
        local TIMES=""
    fi

    # How many characters of the $PWD should be kept
    local pwdmaxlen=20
    local newline=""
    [[ `tput cols` -lt 110 ]] && pwdmaxlen=10
    [[ `tput cols` -lt 85 ]] && newline="\n"

    # Indicate that there has been dir truncation
    local trunc_symbol=".."
    local dir=${PWD##*/}
    pwdmaxlen=$(( ( pwdmaxlen < ${#dir} ) ? ${#dir} : pwdmaxlen ))
    NEW_PWD=${PWD/#$HOME/\~}
    local pwdoffset=$(( ${#NEW_PWD} - pwdmaxlen ))
    if [ ${pwdoffset} -gt "0" ]
    then
        NEW_PWD=${NEW_PWD:$pwdoffset:$pwdmaxlen}
        NEW_PWD=${trunc_symbol}/${NEW_PWD#*/}
    fi
    
    PS1="${TITLEBAR}\
${HC}${TIMES}${ERRPROMPT}\
${HC}[\
${UC}\u\
${HC}${LOC}${HOST_S}\
${UC}${NEW_PWD}\
${HC}]\
$newline${UC}\
\$ ${NONE}"
}

#run once per sheell
function bash_prompt() {

    case $TERM in
     xterm*|rxvt*)
         TITLEBAR='\[\033]0;\u:${NEW_PWD}\007\]'
          ;;
     *)
         TITLEBAR=""
          ;;
    esac
    NONE="\[\033[0m\]"    # unsets color to term's fg color

    # regular colors
    local K="\[\033[0;30m\]"    # black
    local R="\[\033[0;31m\]"    # red
    local G="\[\033[0;32m\]"    # green
    local Y="\[\033[0;33m\]"    # yellow
    local B="\[\033[0;34m\]"    # blue
    local M="\[\033[0;35m\]"    # magenta
    local C="\[\033[0;36m\]"    # cyan
    local W="\[\033[0;37m\]"    # white
    # emphasized (bolded) colors
    local EMK="\[\033[1;30m\]"
    local EMR="\[\033[1;31m\]"
    local EMG="\[\033[1;32m\]"
    local EMY="\[\033[1;33m\]"
    local EMB="\[\033[1;34m\]"
    local EMM="\[\033[1;35m\]"
    local EMC="\[\033[1;36m\]"
    local EMW="\[\033[1;37m\]"
    # background colors
    local BGK="\[\033[40m\]"
    local BGR="\[\033[41m\]"
    local BGG="\[\033[42m\]"
    local BGY="\[\033[43m\]"
    local BGB="\[\033[44m\]"
    local BGM="\[\033[45m\]"
    local BGC="\[\033[46m\]"
    local BGW="\[\033[47m\]"

    source ~/.bash_config

    # user's color
    UC="$config_prompt_user_color"
    HC="$config_prompt_host_color"
    HOST_S="$config_prompt_hostname"


	# LOCation
	LOC="•"
	[ -n "$SSH_CONNECTION" ] && LOC="✈"

	# root's color
    [ $UID -eq "0" ] && UC=$EMR && HC=$EMW

}

trap 'timer_start' DEBUG
PROMPT_COMMAND=bash_prompt_command
bash_prompt
unset bash_prompt
