#!/bin/bash

#this file should configure the capabilities of my systems
NONE="\[$(tput sgr0)\]"
# regular colors
K="\[$(tput sgr0)\]\[$(tput setaf 0)\]" # black
R="\[$(tput sgr0)\]\[$(tput setaf 1)\]"    # red
G="\[$(tput sgr0)\]\[$(tput setaf 2)\]"    # green
Y="\[$(tput sgr0)\]\[$(tput setaf 3)\]"    # yellow
B="\[$(tput sgr0)\]\[$(tput setaf 4)\]"    # blue
M="\[$(tput sgr0)\]\[$(tput setaf 5)\]"    # magenta
C="\[$(tput sgr0)\]\[$(tput setaf 6)\]"    # cyan
W="\[$(tput sgr0)\]\[$(tput setaf 7)\]"    # white
# emphasized (bolded) colors
EMK="\[$(tput bold)\]\[$(tput setaf 0)\]"
EMR="\[$(tput bold)\]\[$(tput setaf 1)\]"
EMG="\[$(tput bold)\]\[$(tput setaf 2)\]"
EMY="\[$(tput bold)\]\[$(tput setaf 3)\]"
EMB="\[$(tput bold)\]\[$(tput setaf 4)\]"
EMM="\[$(tput bold)\]\[$(tput setaf 5)\]"
EMC="\[$(tput bold)\]\[$(tput setaf 6)\]"
EMW="\[$(tput bold)\]\[$(tput setaf 7)\]"
# background colors
BGK="\[$(tput setab 0)\]" # black
BGR="\[$(tput setab 1)\]"    # red
BGG="\[$(tput setab 2)\]"    # green
BGY="\[$(tput setab 3)\]"    # yellow
BGB="\[$(tput setab 4)\]"    # blue
BGM="\[$(tput setab 5)\]"    # magenta
BGC="\[$(tput setab 6)\]"    # cyan
BGW="\[$(tput setab 7)\]"    # white

export config_fancy_effects=0
export config_fancy_borders=0
export config_hdpi=0
export config_ssh_keys=""
export config_dmenu_cache="dmenu_path >$HOME/.cache/dmenu_run"
export config_seafile=0
export config_owncloud=0
export config_locker="lightlocker"
export config_wallpaper_command="$HOME/.config/herbstluftwm/wallpaper.sh"
export config_gui_editor="subl3"
export config_editor="nano"
export config_term="$HOME/bin/start_urxvt"
export config_prompt_user_color="$EMC"
export config_prompt_host_color="$W"
export config_prompt_hostname="$HOSTNAME"
export config_x_colortheme="x_colortheme_material"
export config_x_global_terminal_icon="x_local_terminal_icon"
export config_wallpaper_folder="misc"
export config_startup_sleep=4
export config_is_notebook=0
export config_dotfiles_path="$HOME/git/dotfiles"
export QT_QPA_PLATFORMTHEME="qt5ct" #use qt5ct to set the qt-style

case "$HOSTNAME" in
    "stealthpad")
        export config_term="konsole"
		export config_startup_sleep=1
        export config_wallpaper_folder="2015"
        export config_fancy_effects=1
        export config_fancy_borders=1
        export config_hdpi=1
        export config_ssh_keys="$HOME/.ssh/mykey $HOME/.ssh/cipkey $HOME/.ssh/cb_rsa $HOME/.ssh/uberspace_gitshell $HOME/.ssh/gitlab-cs-fau"
        export config_owncloud=1
        export config_prompt_user_color=$EMY
        export config_prompt_host_color=$B
        export config_prompt_hostname="x240"
        export config_dmenu_cache="$HOME/.config/herbstluftwm/dmenu_run_cache"
        export config_locker="xscreensaver"
        export config_is_notebook=1
        export config_x_global_terminal_icon="x_elementary_terminal_icon"
        ;;
    irene-ThinkPad)
    	export config_ssh_keys="$HOME/.ssh/mykey"
        export config_wallpaper_command="nitrogen --restore &"
        export config_prompt_user_color=$G
        export config_prompt_host_color=$EMB
        export config_prompt_hostname="z61"
    	;;
    faui49man*)
        export config_startup_sleep=8
    	export config_ssh_keys="$HOME/.ssh/i4 $HOME/.ssh/i4github $HOME/.ssh/cipkey"
    	export config_wallpaper_command="feh --bg-center /usr/share/backgrounds/Backyard_Mushrooms_by_Kurt_Zitzelman.jpg"
        export config_locker="gnome-screensaver-command --lock"
        export config_gui_editor="subl"
        export config_prompt_user_color=$B
        export config_prompt_host_color=$EMM
        export config_prompt_hostname=`echo $HOSTNAME | cut -d9 -f2`
        export config_dmenu_cache="$HOME/.config/herbstluftwm/dmenu_run_cache"
        ;;
    faui0*)
        export config_wallpaper_command="(sleep 5 && wallpaper autum)"
    	export config_ssh_keys="$HOME/.ssh/cipkey"
    	export config_locker="xlock"
        export config_prompt_user_color=$C
        export config_prompt_host_color=$EMG
        export config_prompt_hostname="$HOSTNAME"
        ;;
    squarez)
        export config_prompt_user_color=$B
        export config_prompt_host_color=$EMG
        ;;
    horologium.uberspace.de)
        export config_prompt_user_color=$R
        export config_prompt_host_color=$EMC
        export config_prompt_hostname="uber"
        #export TMPDIR=$HOME/tmp
        ;;   
    *)
        ;;
esac

if [[ $config_fancy_effects == 1 ]]; then
    export config_x_transparency="x_true_transparency"
else
    export config_x_transparency="x_fake_transparency"
fi

if [[ $config_hdpi == 1 ]]; then
    export config_x_dpi="x_hdpi"
else
    export config_x_dpi="x_ldpi"
fi
