#!/bin/bash
#only meant for cip/ls4 env
#echo $@ >xtest.log

case $@ in
	herbstluftwm)
	#exec xterm
	# Start a D-Bus session
	source /etc/X11/xinit/xinitrc.d/30-dbus
	# Start GNOME Keyring
	eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
	# You probably need to do this too:
	export SSH_AUTH_SOCK
	export GPG_AGENT_INFO
	export GNOME_KEYRING_CONTROL
	export GNOME_KEYRING_PID
	#end of keyring stuff
	
    	export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
	setxkbmap -option '' 'us international' ',phonetic'
	setxkbmap -option terminate:ctrl_alt_bksp
	exec ssh-agent herbstluftwm -c ~/.config/herbstluftwm/autostart
	;;
	*)
	#exec $@
	exec ssh-agent `dmenu <~/.wmlist`
	exit 0
	#exec /bin/bash -login /etc/X11/Xsession %session
esac

