#!/bin/bash
source ~/.config/herbstluftwm/colors.sh
CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/dmenu_run
cmd=`dmenu -i -nf $COLOR_P_FG1 -sb $COLOR_P_HI -nb $COLOR_P_BG "$@" < "$CACHE"` && exec sh -c "$cmd"
